[package]
name = "shoppinglist-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.6"
log = "0.4.26"
rusqlite = "0.34.0"
serde = { version = "1.0.218", features = ["derive"] }
